
 services:
  api-galp:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=insight
      - POSTGRES_PASSWORD=insight
      - POSTGRES_DB=insightdb

  mongodb:
    image: mongo:latest 
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=insight
      - MONGO_INITDB_ROOT_PASSWORD=insight
      - MONGO_INITDB_DATABASE=insightdb