services:
  api-galp:
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=insightdb

  mongodb:
    image: mongo:latest 
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=insight
      - MONGO_INITDB_ROOT_PASSWORD=insight
      - MONGO_INITDB_DATABASE=insightdb