import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/providers/providers'

const inter = Inter({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  preload: false,
})

export const metadata = {
  title: 'Insight 360',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} font-sans antialiased scroll-smooth`}
      >
        <Providers>
            <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
